feat: llvm `compiler-rt` via osxcross
it adds llvm compiler-rt https://compiler-rt.llvm.org/
compiler-rt can be needed to build code using `__builtin_available()`

it fixes the following error on latest rust-linux-darwin-builder:1.60.0 or earlier

docker run --rm -it -v $PWD:/root/src \
    joseluisq/rust-linux-darwin-builder:1.60.0 \
    sh -c "x86_64-apple-darwin21.1-clang -mmacosx-version-min=10.12 main.c"

Undefined symbols for architecture x86_64:
  "___isOSVersionAtLeast", referenced from:
      _main in main-9c241f.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)